### ISSUE TITLE
django.db.utils.OperationalError: table "web_query" already exists error: failed to create database

### ISSUE THREAD

**Issue by wuyudi** [mathics/Mathics#1008]
I try to run `mathicsserver`

return error:

log

```
Migrating database C:/Users/wuyudi/AppData/Roaming/Python/Mathics/mathics.sqlite
Operations to perform:
  Apply all migrations: auth, contenttypes, sessions, sites, web
Running migrations:
  Applying web.0001_initial...Traceback (most recent call last):
  File "d:\program files\python3.8.5\lib\site-packages\django\db\backends\utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "d:\program files\python3.8.5\lib\site-packages\django\db\backends\sqlite3\base.py", line 411, in execute
    return Database.Cursor.execute(self, query)
sqlite3.OperationalError: table "web_query" already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Program Files\Python3.8.5\Lib\site-packages\mathics\manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "d:\program files\python3.8.5\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "d:\program files\python3.8.5\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "d:\program files\python3.8.5\lib\site-packages\django\core\management\base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "d:\program files\python3.8.5\lib\site-packages\django\core\management\base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "d:\program files\python3.8.5\lib\site-packages\django\core\management\base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "d:\program files\python3.8.5\lib\site-packages\django\core\management\commands\migrate.py", line 243, in handle
    post_migrate_state = executor.migrate(
  File "d:\program files\python3.8.5\lib\site-packages\django\db\migrations\executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "d:\program files\python3.8.5\lib\site-packages\django\db\migrations\executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "d:\program files\python3.8.5\lib\site-packages\django\db\migrations\executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "d:\program files\python3.8.5\lib\site-packages\django\db\migrations\migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "d:\program files\python3.8.5\lib\site-packages\django\db\migrations\operations\models.py", line 92, in database_forwards
    schema_editor.create_model(model)
  File "d:\program files\python3.8.5\lib\site-packages\django\db\backends\base\schema.py", line 324, in create_model
    self.execute(sql, params or None)
  File "d:\program files\python3.8.5\lib\site-packages\django\db\backends\base\schema.py", line 142, in execute
    cursor.execute(sql, params)
  File "d:\program files\python3.8.5\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "d:\program files\python3.8.5\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "d:\program files\python3.8.5\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "d:\program files\python3.8.5\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "d:\program files\python3.8.5\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "d:\program files\python3.8.5\lib\site-packages\django\db\backends\utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "d:\program files\python3.8.5\lib\site-packages\django\db\backends\sqlite3\base.py", line 411, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: table "web_query" already exists
error: failed to create database
```

**Comment by wuyudi** [comment]
Ok, I fixed it, just delete the `mathics.sqlite` in directory.
