### ISSUE TITLE
"cannot import name simplejson"

### ISSUE THREAD

**Issue by dfrankow** [mathics/Mathics#209]
Thanks for your work on mathics.

I get the error below when I try to run "mathics". I think it's due to "python-dev" installing Django 1.7.0. Perhaps you could import simplejson directly? Then I could install it as a separate package. Or perhaps you could have a "requirements.txt" file that has specific versions of things for pip. Not sure how mathics development is structured.

dan@friend:~/Downloads/mathics-dir$ mathics
Traceback (most recent call last):
  File "/usr/local/bin/mathics", line 9, in <module>
    load_entry_point('Mathics==0.6.0rc1', 'console_scripts', 'mathics')()
  File "/usr/local/lib/python2.7/dist-packages/Mathics-0.6.0rc1-py2.7.egg/mathics/main.py", line 214, in main
    definitions = Definitions(add_builtin=True)
  File "/usr/local/lib/python2.7/dist-packages/Mathics-0.6.0rc1-py2.7.egg/mathics/core/definitions.py", line 49, in __init__
    from mathics.builtin import modules, contribute
  File "/usr/local/lib/python2.7/dist-packages/Mathics-0.6.0rc1-py2.7.egg/mathics/builtin/__init__.py", line 21, in <module>
    from mathics.builtin import (
  File "/usr/local/lib/python2.7/dist-packages/Mathics-0.6.0rc1-py2.7.egg/mathics/builtin/graphics.py", line 9, in <module>
    from django.utils import simplejson
ImportError: cannot import name simplejson
dan@friend:~/Downloads/mathics-dir$ python -c "import django; print django.VERSION"
(1, 7, 0, 'final', 0)

**Comment by Flexico** [comment]
I'm not sure how to enforce django==1.6 in master as you say; at the moment I can't run Mathics.

**Comment by sn6uv** [comment]
@Flexico this issue has been fixed (for all versions of django) since Mathics v0.7. We no longer rely on `simplejson`.

I'm closing this issue but please feel free to open another one if you're having issues.

**Comment by Flexico** [comment]
Oh, version 0.6 is still on the site I was downloading from. Now I got the master from Github. X3 Thanks~
