### ISSUE TITLE
Runtime Error after compilation

### ISSUE THREAD

**Issue by Debdut** [mathics/Mathics#244]
I installed Mathics as per instructions. then when I run it by <code>mathics</code> command:

<code>
Traceback (most recent call last):
</code>
<code>
  File "/usr/local/bin/mathics", line 9, in <module>
</code>
<code>
    load_entry_point('Mathics==0.6.0rc1', 'console_scripts', 'mathics')()
</code>
<code>
  File "/usr/local/lib/python2.7/dist-packages/Mathics-0.6.0rc1-py2.7.egg/mathics/main.py", line 214, in main
</code>
<code>
    definitions = Definitions(add_builtin=True)
</code>
<code>
  File "/usr/local/lib/python2.7/dist-packages/Mathics-0.6.0rc1-py2.7.egg/mathics/core/definitions.py", line 49, in __init__
</code>
<code>
    from mathics.builtin import modules, contribute
</code>
<code>
  File "/usr/local/lib/python2.7/dist-packages/Mathics-0.6.0rc1-py2.7.egg/mathics/builtin/__init__.py", line 21, in <module>
</code>
<code>
    from mathics.builtin import (
</code>
<code>
  File "/usr/local/lib/python2.7/dist-packages/Mathics-0.6.0rc1-py2.7.egg/mathics/builtin/graphics.py", line 9, in <module>
</code>
<code>
    from django.utils import simplejson
</code>
<code>
ImportError: cannot import name simplejson
</code>

Also running <code>python setup.py initialize</code> , I get the following error : 

<code>
running initialize
Creating data directory /home/debdut/.local/var/mathics/
Creating database /home/debdut/.local/var/mathics/mathics.sqlite
Traceback (most recent call last):
  File "mathics/manage.py", line 3, in <module>
    from django.core.management import execute_manager
ImportError: cannot import name execute_manager
error: /home/debdut/.local/var/mathics/mathics.sqlite: No such file or directory
</code>

Please help me fix these errors!

**Comment by sn6uv** [comment]
Hi @Debdut thanks for the bug report.

It looks like you're using an outdated version (0.6.0rc1) of Mathics (the website mathics.org is out of date) [Try 0.7 here](https://github.com/mathics/Mathics/releases/download/v0.7rc1/mathics-0.7rc1.tar.gz).

If you're set on using Mathics 0.6 you may have to download to Django 1.5

**Comment by Debdut** [comment]
Yep! Thank you very very much that works!

Also the installing guide is pointing to 0.6rc1, so please change that!

**Comment by sn6uv** [comment]
Thanks for letting me know. I've fixed it now.
