### ISSUE TITLE
Simplify bug

### ISSUE THREAD

**Issue by sn6uv** [mathics/Mathics#304]
```
In[1]:= Integrate[d Sin[t]/ (R^2 + d^2 - 2 R d Cos[t]), {t, 0, Pi}] // Simplify
Traceback (most recent call last):
  File "/usr/bin/mathics", line 9, in <module>
    load_entry_point('Mathics==0.8', 'console_scripts', 'mathics')()
  File "/usr/lib/python2.7/site-packages/Mathics-0.8-py2.7.egg/mathics/main.py", line 311, in main
    shell.evaluate(total_input)
  File "/usr/lib/python2.7/site-packages/Mathics-0.8-py2.7.egg/mathics/main.py", line 117, in evaluate
    out_callback=out_callback)
  File "/usr/lib/python2.7/site-packages/Mathics-0.8-py2.7.egg/mathics/core/evaluation.py", line 207, in __init__
    result = evaluate()
  File "/usr/lib/python2.7/site-packages/Mathics-0.8-py2.7.egg/mathics/core/evaluation.py", line 192, in evaluate
    result = query.evaluate(self)
  File "/usr/lib/python2.7/site-packages/Mathics-0.8-py2.7.egg/mathics/core/expression.py", line 773, in evaluate
    result = rule.apply(new, evaluation, fully=False)
  File "/usr/lib/python2.7/site-packages/Mathics-0.8-py2.7.egg/mathics/core/rules.py", line 116, in apply
    yield_match, expression, {}, evaluation, fully=fully)
  File "/usr/lib/python2.7/site-packages/Mathics-0.8-py2.7.egg/mathics/core/pattern.py", line 225, in match
    yield_head, expression.get_head(), vars, evaluation)
  File "/usr/lib/python2.7/site-packages/Mathics-0.8-py2.7.egg/mathics/core/pattern.py", line 153, in match
    yield_func(vars, None)
  File "/usr/lib/python2.7/site-packages/Mathics-0.8-py2.7.egg/mathics/core/pattern.py", line 217, in yield_head
    yield_choice, expression, attributes, head_vars)
  File "/usr/lib/python2.7/site-packages/Mathics-0.8-py2.7.egg/mathics/core/pattern.py", line 341, in get_pre_choices
    yield_func(vars)
  File "/usr/lib/python2.7/site-packages/Mathics-0.8-py2.7.egg/mathics/core/pattern.py", line 206, in yield_choice
    wrap_oneid=expression.get_head_name() != 'System`MakeBoxes')
  File "/usr/lib/python2.7/site-packages/Mathics-0.8-py2.7.egg/mathics/core/pattern.py", line 506, in match_leaf
    include_flattened=include_flattened)
  File "/usr/lib/python2.7/site-packages/Mathics-0.8-py2.7.egg/mathics/core/pattern.py", line 362, in get_wrappings
    yield_func(items[0])
  File "/usr/lib/python2.7/site-packages/Mathics-0.8-py2.7.egg/mathics/core/pattern.py", line 502, in yield_wrapping
    leaf_count=leaf_count, wrap_oneid=wrap_oneid)
  File "/usr/lib/python2.7/site-packages/Mathics-0.8-py2.7.egg/mathics/builtin/patterns.py", line 539, in match
    self.pattern.match(yield_func, expression, new_vars, evaluation)
  File "/usr/lib/python2.7/site-packages/Mathics-0.8-py2.7.egg/mathics/builtin/patterns.py", line 725, in match
    yield_func(vars, None)
  File "/usr/lib/python2.7/site-packages/Mathics-0.8-py2.7.egg/mathics/core/pattern.py", line 497, in match_yield
    yield_func(new_vars, items_rest)
  File "/usr/lib/python2.7/site-packages/Mathics-0.8-py2.7.egg/mathics/core/rules.py", line 74, in yield_match
    new_expression = self.do_replace(vars, options, evaluation)
  File "/usr/lib/python2.7/site-packages/Mathics-0.8-py2.7.egg/mathics/core/rules.py", line 165, in do_replace
    return self.function(evaluation=evaluation, **vars_noctx)
  File "/usr/lib/python2.7/site-packages/Mathics-0.8-py2.7.egg/mathics/builtin/algebra.py", line 92, in apply
    result = sympy.simplify(result)
File "/usr/lib/python2.7/site-packages/sympy-0.7.6-py2.7.egg/sympy/simplify/simplify.py", line 3708, in simplify
    expr2 = shorter(together(expr, deep=True), together(expr1, deep=True))
  File "/usr/lib/python2.7/site-packages/sympy-0.7.6-py2.7.egg/sympy/polys/rationaltools.py", line 85, in together
    return _together(sympify(expr))
  File "/usr/lib/python2.7/site-packages/sympy-0.7.6-py2.7.egg/sympy/polys/rationaltools.py", line 68, in _together
    return gcd_terms(list(map(_together, Add.make_args(expr))))
  File "/usr/lib/python2.7/site-packages/sympy-0.7.6-py2.7.egg/sympy/polys/rationaltools.py", line 79, in _together
    return expr.__class__(*[ _together(arg) for arg in expr.args ])
  File "/usr/lib/python2.7/site-packages/sympy-0.7.6-py2.7.egg/sympy/polys/rationaltools.py", line 79, in _together
    return expr.__class__(*[ _together(arg) for arg in expr.args ])
  File "/usr/lib/python2.7/site-packages/sympy-0.7.6-py2.7.egg/sympy/polys/rationaltools.py", line 79, in _together
    return expr.__class__(*[ _together(arg) for arg in expr.args ])
  File "/usr/lib/python2.7/site-packages/sympy-0.7.6-py2.7.egg/sympy/polys/rationaltools.py", line 79, in _together
    return expr.__class__(*[ _together(arg) for arg in expr.args ])
  File "/usr/lib/python2.7/site-packages/sympy-0.7.6-py2.7.egg/sympy/polys/rationaltools.py", line 79, in _together
    return expr.__class__(*[ _together(arg) for arg in expr.args ])
  File "/usr/lib/python2.7/site-packages/Mathics-0.8-py2.7.egg/mathics/core/convert.py", line 60, in __new__
    cls, *(expr.head.to_sympy(),) + tuple(leaf.to_sympy()
AttributeError: 'Symbol' object has no attribute 'head'
```

**Comment by sn6uv** [comment]
fixed by #322
