### ISSUE TITLE
Load is not working on local instalation

### ISSUE THREAD

**Issue by fvacek** [mathics/Mathics#382]
When I push the Load button on web interface, nothing happens, server log attached

seems like sqlite database wasn't created correctly during mathicsserver startup

```
Internal Server Error: /ajax/getworksheets/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9c1-py2.7.egg/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9c1-py2.7.egg/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Mathics-0.9-py2.7.egg/mathics/web/views.py", line 287, in get_worksheets
    user__isnull=True).order_by('name').values('name'))
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9c1-py2.7.egg/django/db/models/query.py", line 258, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9c1-py2.7.egg/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9c1-py2.7.egg/django/db/models/query.py", line 112, in __iter__
    for row in compiler.results_iter():
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9c1-py2.7.egg/django/db/models/sql/compiler.py", line 806, in results_iter
    results = self.execute_sql(MULTI)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9c1-py2.7.egg/django/db/models/sql/compiler.py", line 852, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9c1-py2.7.egg/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9c1-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9c1-py2.7.egg/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9c1-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9c1-py2.7.egg/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: web_worksheet
```

**Comment by jaycech3n** [comment]
I've encountered a similar issue before with saving worksheets, the error messages look the same.
https://groups.google.com/forum/#!topic/mathics-users/Id8O-Ka8EFU
