### ISSUE TITLE
Error encountered when calculating integral

### ISSUE THREAD

**Issue by gustavdelius** [mathics/Mathics#62]
Trying to do the integral

  Integrate[x Exp[-x^2/t],{x,0,Infinity}]

gives the error message

Sorry, an error occurred while processing your request!

Without the `t' in the expression the integration still proceeds fine:

  Integrate[x Exp[-x^2/2],{x,0,Infinity}]

correctly gives the answer 1.

I do not know how to tell mathics that t is positive. But 

Integrate[x Exp[-x^2/Abs[t]],{x,0,Infinity}]

gives the same error.

**Comment by sn6uv** [comment]
Update: This is crashing again:

```
In[1]:= Integrate[x Exp[-x^2/t],{x,0,Infinity}]
Traceback (most recent call last):
  File "/home/angus/venv_pypy/bin/mathics", line 11, in <module>
    load_entry_point('Mathics', 'console_scripts', 'mathics')()
  File "/home/angus/Mathics/mathics/main.py", line 286, in main
    result = evaluation.evaluate(query, timeout=settings.TIMEOUT)
  File "/home/angus/Mathics/mathics/core/evaluation.py", line 243, in evaluate
    result = run_with_timeout(evaluate, timeout)
  File "/home/angus/Mathics/mathics/core/evaluation.py", line 63, in run_with_timeout
    return request()
  File "/home/angus/Mathics/mathics/core/evaluation.py", line 226, in evaluate
    result = query.evaluate(self)
  File "/home/angus/Mathics/mathics/core/expression.py", line 861, in evaluate
    result = result.evaluate(evaluation)
  File "/home/angus/Mathics/mathics/core/expression.py", line 858, in evaluate
    result = rule.apply(new, evaluation, fully=False)
  File "/home/angus/Mathics/mathics/core/rules.py", line 73, in apply
    yield_match, expression, {}, evaluation, fully=fully)
  File "/home/angus/Mathics/mathics/core/pattern.py", line 206, in match
    yield_head, expression.get_head(), vars, evaluation)
  File "/home/angus/Mathics/mathics/core/pattern.py", line 135, in match
    yield_func(vars, None)
  File "/home/angus/Mathics/mathics/core/pattern.py", line 198, in yield_head
    yield_choice, expression, attributes, head_vars)
  File "/home/angus/Mathics/mathics/core/pattern.py", line 321, in get_pre_choices
    yield_func(vars)
  File "/home/angus/Mathics/mathics/core/pattern.py", line 187, in yield_choice
    wrap_oneid=expression.get_head_name() != 'System`MakeBoxes')
  File "/home/angus/Mathics/mathics/core/pattern.py", line 478, in match_leaf
    include_flattened=include_flattened)
  File "/home/angus/Mathics/mathics/core/pattern.py", line 353, in get_wrappings
    yield_func(sequence)
  File "/home/angus/Mathics/mathics/core/pattern.py", line 474, in yield_wrapping
    leaf_count=leaf_count, wrap_oneid=wrap_oneid)
  File "/home/angus/Mathics/mathics/builtin/patterns.py", line 761, in match
    self.pattern.match(yield_func, expression, new_vars, evaluation)
  File "/home/angus/Mathics/mathics/builtin/patterns.py", line 1005, in match
    yield_func(vars, None)
  File "/home/angus/Mathics/mathics/core/pattern.py", line 469, in match_yield
    yield_func(new_vars, items_rest)
  File "/home/angus/Mathics/mathics/core/rules.py", line 39, in yield_match
    new_expression = self.do_replace(vars, options, evaluation)
  File "/home/angus/Mathics/mathics/core/rules.py", line 131, in do_replace
    return self.function(evaluation=evaluation, **vars_noctx)
  File "/home/angus/Mathics/mathics/builtin/arithmetic.py", line 1813, in apply
    result = self.to_sympy(Expression('Piecewise', *items.get_sequence()))
  File "/home/angus/Mathics/mathics/builtin/arithmetic.py", line 1848, in to_sympy
    sympy_cases.append((leaves[1].to_sympy(**kwargs), True))
  File "/home/angus/Mathics/mathics/core/expression.py", line 596, in to_sympy
    sympy_expr = builtin.to_sympy(self, **kwargs)
  File "/home/angus/Mathics/mathics/builtin/base.py", line 395, in to_sympy
    return sympy_function(*sympy_args)
  File "/home/angus/venv_pypy/site-packages/sympy-1.0-py2.7.egg/sympy/integrals/integrals.py", line 75, in __new__
    obj = AddWithLimits.__new__(cls, function, *symbols, **assumptions)
  File "/home/angus/venv_pypy/site-packages/sympy-1.0-py2.7.egg/sympy/concrete/expr_with_limits.py", line 368, in __new__
    limits, orientation = _process_limits(*symbols)
  File "/home/angus/venv_pypy/site-packages/sympy-1.0-py2.7.egg/sympy/concrete/expr_with_limits.py", line 69, in _process_limits
    raise ValueError('Invalid limits given: %s' % str(symbols))
ValueError: Invalid limits given: (_Mathics_User_Global`x, 0, oo)
```

This time it's due to an error raised in sympy. I'm not sure what is wrong with those limits however.

**Comment by rocky** [comment]
We are no longer getting tracebacks in computing integrals of this kind.
