### ISSUE TITLE
Repeated pattern results in crash

### ISSUE THREAD

**Issue by wheerd** [mathics/Mathics#697]
I get an error when I try this in Mathics 1.0
on CPython 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]
using SymPy 1.0, mpmath 0.19

```
In[1]:= SetAttributes[f, Orderless]
In[2]:= ReplaceList[f[a, b], f[x___, y___] -> {x, 0, y}]
Traceback (most recent call last):
  File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python36\Scripts\mathics.exe\__main__.py", line 9, in <module>
  File "c:\program files\python36\lib\site-packages\mathics\main.py", line 289, in main
    result = evaluation.evaluate(query, timeout=settings.TIMEOUT)
  File "c:\program files\python36\lib\site-packages\mathics\core\evaluation.py", line 243, in evaluate
    result = run_with_timeout(evaluate, timeout)
  File "c:\program files\python36\lib\site-packages\mathics\core\evaluation.py", line 63, in run_with_timeout
    return request()
  File "c:\program files\python36\lib\site-packages\mathics\core\evaluation.py", line 226, in evaluate
    result = query.evaluate(self)
  File "mathics\core\expression.py", line 871, in mathics.core.expression.Expression.evaluate (mathics/core\expression.c:30612)
  File "mathics\core\expression.py", line 859, in mathics.core.expression.Expression.evaluate.eval_range (mathics/core\expression.c:28674)
  File "mathics\core\expression.py", line 929, in rules (mathics/core\expression.c:29501)
  File "mathics\core\rules.py", line 64, in mathics.core.rules.BaseRule.apply (mathics/core\rules.c:2751)
  File "mathics\core\pattern.py", line 205, in mathics.core.pattern.ExpressionPattern.match (mathics/core\pattern.c:6962)
  File "mathics\core\pattern.py", line 135, in mathics.core.pattern.AtomPattern.match (mathics/core\pattern.c:5168)
  File "mathics\core\pattern.py", line 197, in mathics.core.pattern.ExpressionPattern.match.yield_head (mathics/core\pattern.c:6481)
  File "mathics\core\pattern.py", line 238, in mathics.core.pattern.ExpressionPattern.get_pre_choices (mathics/core\pattern.c:9301)
  File "mathics\core\pattern.py", line 507, in mathics.core.pattern.ExpressionPattern.sort (mathics/core\pattern.c:14740)
  File "mathics\core\pattern.py", line 507, in mathics.core.pattern.ExpressionPattern.sort.lambda (mathics/core\pattern.c:14688)
  File "c:\program files\python36\lib\site-packages\mathics\builtin\base.py", line 495, in get_sort_key
    return self.expr.get_sort_key(pattern_sort=pattern_sort)
AttributeError: 'Repeated' object has no attribute 'expr'
```

**Comment by GarkGarcia** [comment]
This has been fixed.
