### ISSUE TITLE
required field "posonlyargs" missing from arguments

### ISSUE THREAD

**Issue by xdrie** [mathics/Mathics#800]
attempting to run Mathics results in this:
```
❯ mathics
Traceback (most recent call last):
  File "/home/xdrie/.local/bin/mathics", line 8, in <module>
    sys.exit(main())
  File "/home/xdrie/.local/lib/python3.8/site-packages/mathics/main.py", line 242, in main
    definitions = Definitions(add_builtin=True)
  File "/home/xdrie/.local/lib/python3.8/site-packages/mathics/core/definitions.py", line 55, in __init__
    from mathics.builtin import modules, contribute
  File "/home/xdrie/.local/lib/python3.8/site-packages/mathics/builtin/__init__.py", line 7, in <module>
    from mathics.builtin import (
  File "/home/xdrie/.local/lib/python3.8/site-packages/mathics/builtin/arithmetic.py", line 25, in <module>
    from mathics.builtin.lists import _IterationFunction
  File "/home/xdrie/.local/lib/python3.8/site-packages/mathics/builtin/lists.py", line 29, in <module>
    from mathics.builtin.options import options_to_rules
  File "/home/xdrie/.local/lib/python3.8/site-packages/mathics/builtin/options.py", line 15, in <module>
    from mathics.builtin.image import Image
  File "/home/xdrie/.local/lib/python3.8/site-packages/mathics/builtin/image.py", line 13, in <module>
    from mathics.builtin.colors import convert as convert_color, colorspaces as known_colorspaces
  File "/home/xdrie/.local/lib/python3.8/site-packages/mathics/builtin/colors.py", line 70, in <module>
    def _inverse_compand_srgb(x):
  File "/home/xdrie/.local/lib/python3.8/site-packages/mathics/builtin/numpy_utils/with_numpy.py", line 420, in conditional
    f_transformed = transformer.transform()
  File "/home/xdrie/.local/lib/python3.8/site-packages/mathics/builtin/numpy_utils/with_numpy.py", line 333, in transform
    code = compile(tree, '<conditional:%s>'% func_name, 'exec')
TypeError: required field "posonlyargs" missing from arguments
```

**Comment by xdrie** [comment]
looks like this is due to Python version incompatibility. Downgrading to Python 3.6 removed this issue.
