### ISSUE TITLE
mathicsserver fails to initialize

### ISSUE THREAD

**Issue by GarkGarcia** [mathics/Mathics#906]
Here's the traceback:

```
$ mathicsserver
warning: database file /home/pablo/.local/var/mathics/mathics.sqlite not found

Migrating database /home/pablo/.local/var/mathics/mathics.sqlite
Traceback (most recent call last):
  File "/home/pablo/Documents/Mathics/mathics/manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/home/pablo/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/pablo/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/pablo/.local/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/pablo/.local/lib/python3.6/site-packages/django/core/management/base.py", line 361, in execute
    self.check()
  File "/home/pablo/.local/lib/python3.6/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/pablo/.local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 65, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/home/pablo/.local/lib/python3.6/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/pablo/.local/lib/python3.6/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/pablo/.local/lib/python3.6/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/pablo/.local/lib/python3.6/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/pablo/.local/lib/python3.6/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/pablo/.local/lib/python3.6/site-packages/django/urls/resolvers.py", line 571, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/pablo/.local/lib/python3.6/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/pablo/.local/lib/python3.6/site-packages/django/urls/resolvers.py", line 564, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pablo/Documents/Mathics/mathics/urls.py", line 14, in <module>
    url(r'^', include('mathics.web.urls')),
  File "/home/pablo/.local/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pablo/Documents/Mathics/mathics/web/urls.py", line 6, in <module>
    from mathics.web.views import query, main_view, login, logout, save, open, get_worksheets, doc_search, doc_part, doc_chapter, doc_section, doc
  File "/home/pablo/Documents/Mathics/mathics/web/views.py", line 28, in <module>
    documentation.load_pymathics_doc()
  File "/home/pablo/Documents/Mathics/mathics/doc/doc.py", line 727, in load_pymathics_doc
    pymathicsdoc = PyMathicsDocumentation(pymmodule)
  File "/home/pablo/Documents/Mathics/mathics/doc/doc.py", line 765, in __init__
    self.name = self.pymathicsmodule.pymathics_version_data['name']
KeyError: 'name'
error: failed to create database
```

**Comment by rocky** [comment]
Use this patch 
```
diff --git a/pymathics/natlang/__init__.py b/pymathics/natlang/__init__.py
index 5873f82f..860ce16d 100644
--- a/pymathics/natlang/__init__.py
+++ b/pymathics/natlang/__init__.py
@@ -7,6 +7,9 @@ This module provides tools to work with expressions in natural language, using t

 from .natlang import *

-pymathics_version_data = {'author': '',
-                          'version': '0.0.0',
-                          'requires': ['nltk', 'spacy'], }
+pymathics_version_data = {
+    "author": "",
+    "name": "natlang",
+    "version": "0.0.0",
+    "requires": ["nltk", "spacy"],
+}
```

**Comment by rocky** [comment]
I am guessing that the improvements to the autodoc stuff now requires a name where it didn't before. 

And of course missing the name was just wrong anyway.

**Comment by GarkGarcia** [comment]
> Use this patch
> 
> ```
> diff --git a/pymathics/natlang/__init__.py b/pymathics/natlang/__init__.py
> index 5873f82f..860ce16d 100644
> --- a/pymathics/natlang/__init__.py
> +++ b/pymathics/natlang/__init__.py
> @@ -7,6 +7,9 @@ This module provides tools to work with expressions in natural language, using t
> 
>  from .natlang import *
> 
> -pymathics_version_data = {'author': '',
> -                          'version': '0.0.0',
> -                          'requires': ['nltk', 'spacy'], }
> +pymathics_version_data = {
> +    "author": "",
> +    "name": "natlang",
> +    "version": "0.0.0",
> +    "requires": ["nltk", "spacy"],
> +}
> ```

Just I did this. I also made it so that `mathicsserver` doesn't crash when `pymathics_version_data` is malformed.

**Comment by mmatera** [comment]
Yes, I should add some code to fill a default name in case this field be empty...
